1) What is a Decision Tree?

-A Decision Tree is a supervised machine learning algorithm used for both classification and regression tasks.
- In classification problems, it predicts the class label of an observation by learning simple decision rules inferred from the data features.
- It resembles a tree-like structure, where decisions are made step by step.

Structure of a Decision Tree

- Root Node: The starting point of the tree representing the entire dataset.
- Decision Nodes: Intermediate nodes where the data is split based on a feature.
- Branches:  Outcomes of a decision rule.
- Leaf Nodes (Terminal Nodes):  Final nodes that provide the predicted class label.

How a Decision Tree Works in Classification
The algorithm selects the best feature to split the data based on criteria such as:

-Gini Impurity
-Entropy (Information Gain)
It divides the dataset into subsets where each subset becomes more homogeneous (i.e., contains similar class labels).This splitting process continues recursively until:

  -The data is sufficiently pure, or
  - A stopping condition (like maximum depth) is reached.

The final prediction is made by following the path from the root node to a leaf node.

2) Gini Impurity and Entropy as Impurity Measures

In a Decision Tree, impurity measures are used to determine how well a feature separates the data into distinct classes. The goal is to create splits that make each resulting group as pure as possible.

Gini Impurity:

- Gini Impurity measures the probability of incorrectly classifying a randomly chosen observation if it were randomly labeled according to the class distribution in that node.
- Its value ranges between 0 and 0.5 (for binary classification).
- A Gini value of 0 indicates perfect purity, meaning all observations in the node belong to one class.
- It is computationally efficient and commonly used as the default criterion in many implementations.

Interpretation:

Lower Gini Impurity indicates a better split because the resulting nodes contain more homogeneous class labels.

Entropy

 - Entropy measures the level of randomness or disorder in the data.
 - It ranges from 0 to 1 (in binary classification).
 - An Entropy value of 0 indicates complete purity, while higher values indicate more mixed classes.
 - It is based on the concept of Information Gain.

Information Gain is calculated as the reduction in entropy after a split.

Interpretation:
Lower Entropy after splitting indicates a more effective feature for classification.

Impact on Decision Tree Splits

At each step, the algorithm evaluates all possible splits.
- It selects the feature that results in the greatest reduction in impurity.
- For Gini, it minimizes Gini Impurity.
- For Entropy, it maximizes Information Gain.
- Both measures aim to produce nodes that are as pure as possible.

In practice, both criteria often lead to similar tree structures, though Gini is slightly faster to compute, while Entropy provides a more theoretical interpretation grounded in information theory.

3)Difference Between Pre-Pruning and Post-Pruning in Decision Trees

Pruning is a technique used to reduce overfitting in Decision Trees by controlling their complexity. It helps improve the model’s ability to generalize to new data.

Pre-Pruning (Early Stopping)

- Pre-pruning stops the growth of the tree during the training process.
- The tree is prevented from growing beyond a certain limit based on predefined conditions.
- Common stopping criteria include:

- Maximum depth of the tree
- Minimum number of samples required to split
- Minimum impurity decrease

Practical Advantage:

It reduces computational cost and training time because the tree is restricted from becoming too deep.

Post-Pruning (Backward Pruning)

Post-pruning allows the tree to grow fully and then removes branches that do not contribute significantly to predictive performance.

-It evaluates subtrees and replaces them with leaf nodes if doing so improves validation accuracy.
- Common methods include cost-complexity pruning.

Practical Advantage:

-It generally produces better generalization performance because pruning decisions are based on the fully grown tree and validation results.

Key Difference:

-Pre-pruning controls tree growth before it becomes complex.
-Post-pruning simplifies an already fully grown tree.

In summary, pre-pruning focuses on preventing over-complexity early, while post-pruning focuses on correcting over-complexity after full tree construction.

4) Information Gain in Decision Trees

Information Gain is a measure used to evaluate how well a particular feature separates the training data into distinct classes. It is based on the concept of Entropy, which measures the level of disorder or uncertainty in a dataset.

Definition:

Information Gain represents the reduction in Entropy after a dataset is split on a feature.

It is calculated as:

  Information Gain = Entropy (parent node) − Weighted Entropy (child nodes)

A higher value indicates a greater reduction in uncertainty.

Why It Is Important for Choosing the Best Split

-In a Decision Tree, the objective is to create nodes that are as pure as possible.
Information Gain helps identify the feature that most effectively reduces randomness in the data.
-At each node, the algorithm calculates the Information Gain for all possible features.
The feature with the highest Information Gain is selected for splitting.

Impact on Tree Construction:

-Ensures that each split improves classification clarity.
-Leads to more homogeneous child nodes.
-Contributes to building an efficient and interpretable tree structure.

In essence, Information Gain guides the Decision Tree in selecting the most informative feature at each step, thereby improving classification accuracy and model performance.

5) Common Real-World Applications of Decision Trees

- Healthcare Diagnosis:
  Used to classify diseases based on patient symptoms, medical history, and test results.

- Finance and Credit Scoring:
  Applied in loan approval systems to assess credit risk and detect potential defaults.

- Marketing and Customer Segmentation:
  Helps businesses identify customer groups and predict purchasing behavior.

- Fraud Detection:
  Used in banking and insurance to detect suspicious transactions.

- Human Resource Management:
  Assists in predicting employee attrition or performance levels.

Main Advantages of Decision Trees

- Easy to Interpret and Visualize:
  The tree structure is intuitive and understandable, even for non-technical stakeholders.

- Minimal Data Preparation:
  Requires little preprocessing compared to many other algorithms.

- Handles Different Types of Data:
  Works with both numerical and categorical variables.

- Non-Parametric Nature:
  Does not assume any specific data distribution.

Main Limitations of Decision Trees

Prone to Overfitting:
  Deep trees may memorize training data and perform poorly on unseen data.

Instability:
  Small changes in the dataset can lead to different tree structures.

Bias Toward Dominant Classes:
  If data is imbalanced, the model may favor the majority class.

Lower Predictive Accuracy Alone:
  Single trees may not perform as well as ensemble methods like Random Forest.

In summary, Decision Trees are powerful and interpretable models widely used in practice, but they require careful tuning to avoid overfitting and instability.

In [1]:
# 6) WAPP to implement Decision Tree Classifier using the Gini criterion
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')
print("All Libraries are successfully imported")

All Libraries are successfully imported

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.DESCR) # gives data set in an organised way

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [3]:
# we convert bunch object into data frame
df = pd.DataFrame(iris.data,columns = iris.feature_names)
df['target'] = iris.target

In [4]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [5]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [6]:
df.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [7]:
df.sample(3)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
133,6.3,2.8,5.1,1.5,2
149,5.9,3.0,5.1,1.8,2
111,6.4,2.7,5.3,1.9,2

In [8]:
X = iris.data
y = iris.target # here we load the iris dataset

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=1)

In [12]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion = 'gini',random_state=1)
model

DecisionTreeClassifier(random_state=1)

In [13]:
model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=1)

In [14]:
y_pred = model.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
print("Model Accuracy:", accuracy)

Model Accuracy: 0.9555555555555556

In [16]:
for feature, importance in zip(iris.feature_names, model.feature_importances_):
    print(f"{feature}: {importance}")

sepal length (cm): 0.02146946564885496
sepal width (cm): 0.02146946564885496
petal length (cm): 0.0631695426262108
petal width (cm): 0.8938915260760792

In [17]:
# from the above output it is clear that features are ranked in following way of importance: 
#Petal width > Petal length > Sepal features

In [18]:
#7.WAP in python to load iris data set Train a Decision Tree Classifier with max_depth=3 and 
#compare its accuracy to a fully-grown tree
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [19]:
from sklearn.datasets import load_iris

In [20]:
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [21]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)
df['target'] = iris.target

In [22]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [23]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [24]:
df.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [26]:
X = iris.data
y = iris.target #Loading the Data

In [29]:
# Split the Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 1)

In [30]:
# Train the Data using the Decesion Treee Model
from sklearn.tree import DecisionTreeClassifier
Decision_Tree = DecisionTreeClassifier()
Decision_Tree

DecisionTreeClassifier()

In [31]:
#Full Tree
full_tree = DecisionTreeClassifier( random_state = 1)
full_tree.fit(X_train,y_train)

DecisionTreeClassifier(random_state=1)

In [32]:
from sklearn.metrics import accuracy_score
y_pred_full = full_tree.predict(X_test)
accuracy_full = accuracy_score(y_test,y_pred_full)
print("Fully Grown Tree Accuracy:", accuracy_full)

Fully Grown Tree Accuracy: 0.9555555555555556

In [33]:
#limited tree where max =3
limited_tree = DecisionTreeClassifier(max_depth=3, random_state=42)
limited_tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [34]:
y_pred_limited = limited_tree.predict(X_test)
accuracy_limited = accuracy_score(y_test, y_pred_limited)

print("Max Depth = 3 Accuracy:", accuracy_limited)

Max Depth = 3 Accuracy: 0.9555555555555556

In [35]:
# Here the values both are same it is clear case of overfitting.

In [36]:
#.Write a Python program to Load the Boston Housing Dataset Train a Decision Tree Regressor &
# Print the Mean Squared Error (MSE) and feature importances
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [37]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
print(housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33 (1997) 291-297

In [38]:
df = pd.DataFrame(housing.data,columns = housing.feature_names)
df['target'] = housing

In [39]:
X = housing.data
y = housing.target

In [40]:
X

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8))

In [41]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,))

In [42]:
X.shape

(20640, 8)

In [43]:
y.shape

(20640,)

In [44]:
from sklearn.model_selection  import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.3,random_state = 1)

In [45]:
from sklearn.tree import DecisionTreeRegressor
Decision_tree = DecisionTreeRegressor()
Decision_tree

DecisionTreeRegressor()

In [46]:
DecisionTreeRegressor(random_state=1)

DecisionTreeRegressor(random_state=1)

In [53]:
model = DecisionTreeRegressor(random_state=1)
model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=1)

In [54]:
from sklearn.metrics import r2_score, mean_squared_error
y_pred = model.predict(X_test)

In [55]:
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R2 Score:", r2)
print("Mean Squared Error:", mse)

R2 Score: 0.6266979002298886
Mean Squared Error: 0.49077395341813623

In [58]:

#print feature importance with fearture names
for feature, importance in zip(housing.feature_names, model.feature_importances_):
    print(f"{feature}: {importance}")

MedInc: 0.5106672676746705
HouseAge: 0.05070627231875136
AveRooms: 0.03061995033515703
AveBedrms: 0.027599094468887857
Population: 0.026735525041190575
AveOccup: 0.13843076678085642
Latitude: 0.10883998140135692
Longitude: 0.10640114197912937

In [ ]:
# Income > Occupancy > Location > House Age > Room details

# This makes real-world sense because: Wealthier neighborhoods = higher house prices Location strongly affects value

In [57]:
#9.WAP in python to load iris data set Train a Decision Tree Classifier max_depth and min_samples_split 
#using GridSearchCV Print the best parameters and the resulting model accuracy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [73]:
from sklearn.datasets import load_iris
iris = load_iris()

In [74]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)
df['target'] = iris.target

In [63]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [64]:
df.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [65]:
from sklearn.model_selection import train_test_split,GridSearchCV
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 1)

In [66]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt

DecisionTreeClassifier(random_state=42)

In [70]:
#Define Parameter Grid
param_grid = {
    'max_depth': [2, 3, 4, 5, None],
    'min_samples_split': [2, 5, 10]
}

In [71]:
# Apply GridSearchCV
grid_search = GridSearchCV(
    estimator=dt,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy'
)
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'max_depth': [2, 3, 4, 5, None],
                         'min_samples_split': [2, 5, 10]},
             scoring='accuracy')

In [72]:
# Get Best Parameters
print("Best Parameters:", grid_search.best_params_)

# Get Best Model
best_model = grid_search.best_estimator_

# Predict on Test Data
y_pred = best_model.predict(X_test)

# Calculate Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

Best Parameters: {'max_depth': 4, 'min_samples_split': 10}
Model Accuracy: 1.0



10) Disease Prediction Using Decision Tree – Step-by-Step Approach

If I were working as a data scientist in a healthcare company to predict whether a patient has a disease, I would follow a systematic and careful process. Since healthcare decisions impact real lives, the approach must be accurate, interpretable, and reliable.

 1. Handling Missing Values

Healthcare datasets often contain missing values due to incomplete medical records, skipped tests, or human errors.

-Steps I would follow:

- First, analyze how much data is missing in each column.
- Identify whether the missing values are in numerical or categorical features.
- If the percentage of missing values is small:

  - Replace numerical missing values with **mean or median** (median is preferred if data has outliers).
  - Replace categorical missing values with the **most frequent category (mode)**.
- If a column has too many missing values and is not very important, I may consider dropping it.
- Ensure that missing value treatment is done carefully to avoid data leakage.

This step ensures the dataset becomes clean and suitable for model training.

2. Encoding Categorical Features

Machine learning models cannot understand text-based categories such as “Male/Female” or “Yes/No.” Therefore, categorical features must be converted into numerical format.

Approach:

- For binary categories (Yes/No), use simple label encoding.
- For nominal categories (like blood group or city), use One-Hot Encoding.
- For ordinal categories (like disease stage: Mild, Moderate, Severe), use ordinal encoding while maintaining order.

Proper encoding ensures the model correctly interprets the categorical information.

3. Training the Decision Tree Model

Once preprocessing is complete:

- Split the dataset into training and testing sets.
- Use the training data to build a Decision Tree Classifier.

A Decision Tree is a good choice in healthcare because:

- It is easy to interpret and explain to doctors.
- It handles both numerical and categorical data.
- It captures non-linear relationships.
- It does not require feature scaling.

The model learns patterns from patient features (age, symptoms, test results) to predict whether the disease is present.

4. Hyperparameter Tuning

Decision Trees can easily overfit the training data. To avoid this, I would tune important hyperparameters such as:

-max_depth – Controls how deep the tree grows.
-min_samples_split – Minimum samples required to split a node.
-min_samples_leaf – Minimum samples required at a leaf node.

I would use GridSearchCV with cross-validation to try different combinations and select the best-performing model.

This ensures the model generalizes well to new patients.

5. Evaluating Model Performance

In healthcare, accuracy alone is not sufficient.

I would evaluate the model using:

Accuracy – Overall correctness.
Precision – Important to reduce false alarms.
Recall (Sensitivity) – Extremely important because missing a sick patient is dangerous
F1-score – Balance between precision and recall.
Confusion Matrix – To understand prediction errors clearly.
ROC-AUC score– To measure overall classification ability.

In disease prediction, recall is usually the most important metric because we want to minimize false negatives.

Business Value in Real-World Healthcare

This model can provide significant benefits:

1. Early Disease Detection

Patients at high risk can be identified early, improving treatment outcomes.

2. Better Clinical Decision Support

Doctors can use the model as a support tool to assist diagnosis.

3. Reduced Healthcare Costs

Early detection prevents expensive advanced treatments.

 4. Improved Resource Allocation

Hospitals can prioritize high-risk patients.

5. Personalized Treatment Plans

Patients can receive care based on their predicted risk level.

Conclusion

By carefully handling missing values, encoding categorical data, training and tuning a Decision Tree model, and evaluating it with appropriate metrics, we can build a reliable disease prediction system.

Such a system not only improves prediction accuracy but also adds real value by supporting doctors, reducing costs, and ultimately saving lives.